workflows:
  android-workflow:
    name: Android Workflow
    environment:
      groups:
        - linux
      xcode: latest
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build Android app
        script: flutter build apk
